name: Android Release Deployment

on:
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_to_play_store:
    name: Deploy Android App to Google Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Cache Gradle and Java
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            ~/.m2/repository
            ~/.java
          key: ${{ runner.os }}-gradle-java-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-java-

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Generate local.properties
        run: |
          echo "sdk.dir=${{ secrets.SDK_LOCATION }}" > local.properties
          echo "ADMOB_APP_ID_APPLICATION=${{ secrets.ADMOB_APP_ID_APPLICATION }}" >> local.properties
          echo "ADMOB_APP_ID_TEST=${{ secrets.ADMOB_APP_ID_TEST }}" >> local.properties
          echo "ADMOB_APP_ID_PROD=${{ secrets.ADMOB_APP_ID_PROD }}" >> local.properties

      - name: Increment App Version Code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}
          
      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          alias: ${{ secrets.APP_NAME_KEY }}
          keyPassword: ${{ secrets.APP_NAME_KEY_PASSWORD }}

      - name: Set Up Google Play Store Authorization
        run: echo '${{ secrets.GOOGLE_PLAY_API_AUTH }}' > service_account.json

      - name: Upload Release to Google Play Store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: service_account.json
          packageName: com.lucassimao.notaalvo
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: production
          status: 'completed'
