name: Android Release Deployment

on:
  pull_request:
    branches: [ "master" ]

jobs:
  deploy_to_play_store:
    name: Deploy Android App to Google Play Store
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1

      - name: Cache Gradle and Java
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle
            ~/.m2/repository
            ~/.java
          key: ${{ runner.os }}-gradle-java-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-java-

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Load Google Service File
        env:
          DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: echo $DATA | base64 -di > app/google-services.json

      - name: Decode and Save Keystore File
        env:
          KEYSTORE_FILE_BASE64: ${{ secrets.KEYSTORE }}
        run: |
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > app/key_app_nota_alvo.jks

      - name: Create local.properties
        run: |
          echo "sdk.dir=${{ secrets.SDK_LOCATION }}" > local.properties
          echo "ADMOB_APP_ID_APPLICATION=${{ secrets.ADMOB_APP_ID_APPLICATION }}" >> local.properties
          echo "ADMOB_APP_ID_TEST=${{ secrets.ADMOB_APP_ID_TEST }}" >> local.properties
          echo "ADMOB_APP_ID_PROD=${{ secrets.ADMOB_APP_ID_PROD }}" >> local.properties
          echo "storeFile=key_app_nota_alvo.jks" >> app/keystore.properties
          echo "$KEYSTORE_FILE_BASE64" | base64 --decode > app/keystore.jks
          echo "storePassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> app/keystore.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> app/keystore.properties

      - name: Increment App Version Code
        uses: chkfung/android-version-actions@v1.2.1
        with:
          gradlePath: app/build.gradle.kts
          versionCode: ${{ github.run_number }}

      - name: Build Android Bundle
        run: ./gradlew bundle
        env:
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          STORE_PASSWORD: ${{ secrets.KEY_PASSWORD }}
          
      - name: Sign Android Release
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.KEYSTORE }}
          keyStorePassword: ${{ secrets.KEY_PASSWORD }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Set Up Google Play Store Authorization
        run: echo '${{ secrets.GOOGLE_PLAY_API_AUTH }}' > service_account.json

      - name: Upload Release to Google Play Store
        uses: r0adkll/upload-google-play@v1.1.1
        with:
          serviceAccountJson: service_account.json
          packageName: com.lucassimao.notaalvo
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: alpha
          status: 'completed'
